#!/bin/bash
echo "📦 VikingBoard - Recommended KiCad Plugins"
echo "=========================================="
echo ""
echo "Open KiCad and install these plugins:"
echo ""
echo "1. ⭐⭐⭐ Interactive HTML BOM (CRITICAL)"
echo "   - For assembly/soldering reference"
echo ""
echo "2. ⭐⭐ FreeRouting (CRITICAL)"
echo "   - Auto-route 40 unconnected traces"
echo ""
echo "3. ⭐⭐ Fabrication Toolkit"
echo "   - JLCPCB BOM/CPL automation"
echo ""
echo "4. ⭐ Board2PDF"
echo "   - Documentation export"
echo ""
echo "5. ⭐ Via Patterns"
echo "   - GND stitching (important for RF)"
echo ""
echo "6. ⭐ Round Tracks"
echo "   - RF trace optimization"
echo ""
echo "7. Gerber to Order"
echo "   - Quick gerber export"
echo ""
echo ""
echo "📋 Installation steps:"
echo "  1. Open KiCad"
echo "  2. Tools → Plugin and Content Manager"
echo "  3. Search for plugin name"
echo "  4. Click Install"
echo "  5. Apply Pending Changes"
echo "  6. Restart KiCad"
echo ""
echo "⏱️  Estimated install time: 5-10 minutes"
