#!/usr/bin/env python3
"""
vikingboard_nets.py - Sync nets from VikingBoard spec to KiCad PCB.

Intended use:
- Run inside KiCad 9 pcbnew Python shell (SWIG API, deprecated but still available).
- Uses DRY_RUN flag to preview vs. apply changes.
"""

import pcbnew  # KiCad's Python API (deprecated SWIG bindings in KiCad 9)
from pathlib import Path
from typing import Dict, List, Tuple
import csv

# Toggle this to actually write changes
DRY_RUN = True

# Path to repo root and docs
REPO_ROOT = Path("/Users/taj/vikingboard")  # adjust if needed
DOCS_CSV = REPO_ROOT / "docs" / "vikingboard_nets.csv"


def iter_net_rows_from_csv(csv_path: Path) -> List[Tuple[str, str, str]]:
    """
    Read (ref,pad,net) from the CSV generated by vikingboard_docs.py.
    Expected header: Ref,Pad,Net,...
    """
    rows: List[Tuple[str, str, str]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            ref = row.get("Ref")
            pad = row.get("Pad")
            net = row.get("Net")
            if not ref or not pad or not net:
                continue
            rows.append((ref.strip(), pad.strip(), net.strip()))
    return rows


def build_spec_dict(rows: List[Tuple[str, str, str]]) -> Dict[Tuple[str, str], str]:
    """
    Build a dict keyed by (ref, pad) -> net.
    """
    spec: Dict[Tuple[str, str], str] = {}
    for ref, pad, net in rows:
        key = (ref, pad)
        spec[key] = net
    return spec


def get_board() -> pcbnew.BOARD:
    """
    Get the current board from pcbnew.
    """
    board = pcbnew.GetBoard()
    if board is None:
        raise RuntimeError("No board loaded in pcbnew. Open Vikingboard.kicad_pcb first.")
    return board


def find_footprint(board: pcbnew.BOARD, ref: str):
    """
    Find a footprint by reference designator.
    """
    for fp in board.GetFootprints():
        if fp.GetReference() == ref:
            return fp
    return None


def ensure_net(board: pcbnew.BOARD, net_name: str) -> pcbnew.NETINFO_ITEM:
    """
    Ensure a net with given name exists on the board, return it.
    """
    netcode = board.GetNetcodeFromNetname(net_name)
    if netcode != pcbnew.NETINFO_LIST.UNCONNECTED:
        return board.FindNet(net_name)

    # Create new net
    netinfo = pcbnew.NETINFO_ITEM(board, net_name)
    board.Add(netinfo)
    return netinfo


def apply_nets_from_spec(spec: Dict[Tuple[str, str], str]):
    board = get_board()
    total = len(spec)
    pads_not_found = 0
    fp_not_found = 0
    changed = 0

    print("=== VikingBoard net-script ===")
    print(f"Mode: {'DRY_RUN' if DRY_RUN else 'APPLY'}")
    print(f"[INFO] Total spec entries: {total}")

    for (ref, padname), net_name in spec.items():
        fp = find_footprint(board, ref)
        if fp is None:
            print(f"[ERROR] Footprint not found for ref {ref}")
            fp_not_found += 1
            continue

        pad = fp.FindPadByNumber(str(padname))
        if pad is None:
            print(f"[ERROR] Pad '{padname}' not found on footprint {ref}")
            pads_not_found += 1
            continue

        current_net = pad.GetNet()
        current_name = current_net.GetNetname() if current_net else "<no net>"

        if current_name == net_name:
            continue

        print(f"[CHANGE] {ref}.{padname}: {current_name} -> {net_name}")

        if not DRY_RUN:
            netinfo = ensure_net(board, net_name)
            pad.SetNet(netinfo)
            changed += 1

    print("\\n--- Summary ---")
    print(f"Total spec entries  : {total}")
    print(f"Footprints not found: {fp_not_found}")
    print(f"Pads not found      : {pads_not_found}")
    print(f"Pads changed        : {changed}")
    if DRY_RUN:
        print("\\n[NOTE] DRY_RUN is True. No changes were written to the board.")
        print("       Set DRY_RUN = False and reload the module to apply changes.")
    else:
        print("\\n[NOTE] Changes written to the board. Save the PCB to persist.")


def print_markdown_preview(spec: Dict[Tuple[str, str], str]):
    rows = list(spec.items())
    print("\\n--- Markdown pin map (from spec) ---")
    print("| Ref | Pad | Net |")
    print("| :-- | :-- | :-- |")
    for (ref, pad), net in sorted(rows):
        print(f"| {ref} | {pad} | `{net}` |")


def main():
    rows = iter_net_rows_from_csv(DOCS_CSV)
    print(f"[INFO] iter_net_rows_from_csv() yielded {len(rows)} rows")
    spec = build_spec_dict(rows)
    print(f"[INFO] Normalized {len(spec)} spec entries")

    apply_nets_from_spec(spec)
    print_markdown_preview(spec)


if __name__ == "__main__":
    main()
